version: "3"
services:
    web:
        image: trafex/php-nginx
        ports:
            - 80:8080
        volumes:
            - .:/var/www/html
    db:
        image: mariadb
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: m3
            MYSQL_ROOT_PASSWORD: rootpass
        volumes:
            - m3data:/var/lib/mysql
            - ./.sql/m3.skeleton.sql:/docker-entrypoint-initdb.d/m3.skeleton.sql:ro
    adminer:
        image: adminer
        ports:
            - 8080:8080
        # volumes:
        #     - ./.sql/m3-db-2023-11-21.gz:/var/www/html/adminer.sql.gz:ro
volumes:
    m3data: {}
